
ALTER TABLE public.clients 
ADD COLUMN IF NOT EXISTS age integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS weight numeric DEFAULT NULL,
ADD COLUMN IF NOT EXISTS height numeric DEFAULT NULL,
ADD COLUMN IF NOT EXISTS experience text DEFAULT 'مبتدئ',
ADD COLUMN IF NOT EXISTS days_per_week integer DEFAULT 4,
ADD COLUMN IF NOT EXISTS injuries text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS preferred_equipment text DEFAULT NULL;
